Fixes small details in common metrics
digital-asset/docs.daml.com pull request #194
Opened 2023-03-07 17:48 UTC by lucb-da

* values in `service` label uses `_`, not `-`
* the paths usually start with a version segment

2023-03-07 17:53 UTC, miklos-da approved these changes

2023-03-07 18:01 UTC, davidd-da approved these changes

2023-03-08 10:47 UTC, garyverhaegen-da requested changes
At this point in the process, please mirror changes to 2.6 to 2.7.

2023-03-08 17:55 UTC, garyverhaegen-da commented
> > At this point in the process, please mirror changes to 2.6 to 2.7.
> 
> What do you mean? Cannot we merge these changes to `main` anyway?

We don't use release branches in this repo, we just have one folder per version. If the changes made here are also relevant for the main branch of development, you should do the same changes to the `docs/2.7.0` folder as you made in `docs/2.6.0`.

2023-03-08 18:24 UTC, garyverhaegen-da commented
> > > At this point in the process, please mirror changes to 2.6 to 2.7.
> > 
> > 
> > What do you mean? Cannot we merge these changes to `main` anyway?
> 
> We don't use release branches in this repo, we just have one folder per version. If the changes made here are also relevant for the main branch of development, you should do the same changes to the `docs/2.7.0` folder as you made in `docs/2.6.0`.

(If this should target _just_ the main branch of development and the change this documents isn't included in the 2.6 RC, then this change should _only_ be made to `docs/2.7`.)

2023-03-09 12:05 UTC, miklos-da commented
> > > > At this point in the process, please mirror changes to 2.6 to 2.7.
> > > 
> > > 
> > > What do you mean? Cannot we merge these changes to `main` anyway?
> > 
> > 
> > We don't use release branches in this repo, we just have one folder per version. If the changes made here are also relevant for the main branch of development, you should do the same changes to the `docs/2.7.0` folder as you made in `docs/2.6.0`.
> 
> (If this should target _just_ the main branch of development and the change this documents isn't included in the 2.6 RC, then this change should _only_ be made to `docs/2.7`.)

Ah, OK, makes sense — thanks for providing more context.

2023-03-09 14:14 UTC, garyverhaegen-da commented
> Made the change in 2.7.0 too. This information is valid from 2.6.0 onward.

Thanks!

2023-03-09 14:14 UTC, garyverhaegen-da approved these changes

2023-03-09 14:23 UTC, merged