#15209 Remove agreement text from Daml
digital-asset/docs.daml.com pull request #639
Opened 2024-02-09 08:38 UTC by hubert-da

2024-02-09 08:49 UTC, stefanobaghino-da commented
IIUC the docs are frozen for 3.x, but someone from @digital-asset/daml-docs can confirm.

2024-02-09 08:58 UTC, hubert-da commented
Based on the info, moving it to the `draft` dir.

2024-02-09 10:09 UTC, garyverhaegen-da commented
`draft` is meant for features that are in a draft status, i.e. they're so alpha/preview/lab that we don't even want them in the main documentation. `draft` is not meant to be a draft of the next documentation for features we know will be in. That _should_ be what `3.0.0` is for, but the current version of the `3.0.0` docs is a bit of a mess and we're waiting for the Canton team to figure out how to work with docs in the 3.x era before we can work on the 3.x docs.

2024-02-09 10:17 UTC, hubert-da commented
Thanks @garyverhaegen-da and @stefanobaghino-da. Leaving the PR in a draft then.

2024-02-09 14:16 UTC, garyverhaegen-da commented
> > the current version of the `3.0.0` docs is a bit of a mess and we're waiting for the Canton team to figure out how to work with docs in the 3.x era before we can work on the 3.x docs.
> 
> The delay is not because of the Canton team but because we have some k8s docs in `3.0.0` that are actively used by customers and don't live anywhere else. We should have a new OSS home for them "soon."
> 
> Thanks for your patience, @hubert-da (and everyone!)

I think we have two separate issues here. On the one hand, as you explained, we cannot currently delete the existing, problematic, out-of-date `3.0.0` folder, because external people depend on it. It is an issue because it creates confusion, as in this PR.

On the other hand, if this folder were deleted right now, we also couldn't start on the "new" `3.0` folder, because the canton repo is not producing a docs bundle with its 3.x snapshots.

2024-03-28 09:15 UTC, garyverhaegen-da commented
We have [started the 3.1 documentation folder "for real"](https://github.com/digital-asset/docs.daml.com/pull/675). It looks like this pull request was trying to make changes to 3.0.0, which has now been completely deleted. Please update it to target 3.1 instead.

2024-06-12 16:55 UTC, cathyjung-da requested changes
I made a few minor suggestions. Otherwise LGTM. Thank you.

2024-06-12 16:55 UTC, cathyjung-da commented on docs/3.0.0/docs/concepts/ledger-model/ledger-integrity.rst
> +#. an `Iou obligor owner` contract has only the `obligor` as a signatory.
```suggestion
#. An `Iou obligor owner` contract has only the `obligor` as a signatory.
```

2024-06-12 16:55 UTC, cathyjung-da commented on docs/3.0.0/docs/concepts/ledger-model/ledger-integrity.rst
>  #. a `MustPay obligor owner` contract has both the `obligor`
```suggestion
#. A `MustPay obligor owner` contract has both the `obligor`
```

2024-06-12 16:55 UTC, cathyjung-da commented on docs/3.0.0/docs/concepts/ledger-model/ledger-integrity.rst
>  #. a `PaintOffer houseOwner painter obligor refNo` contract has only the
```suggestion
#. A `PaintOffer houseOwner painter obligor refNo` contract has only the
```

2024-06-12 16:55 UTC, cathyjung-da commented on docs/3.0.0/docs/concepts/ledger-model/ledger-integrity.rst
>  #. a `PaintAgree houseOwner painter refNo` contract has both the
```suggestion
#. A `PaintAgree houseOwner painter refNo` contract has both the
```

2024-06-12 16:55 UTC, cathyjung-da commented on docs/3.0.0/docs/concepts/ledger-model/ledger-integrity.rst
> +**Exercise** actions on the contract allowed by the contract model, and
```suggestion
**Exercise** actions on the contract allowed by the contract model.
```

2024-06-12 16:55 UTC, cathyjung-da commented on docs/3.0.0/docs/concepts/ledger-model/ledger-integrity.rst
> +the exercise actions the party can perform according to the authorization
```suggestion
the exercise actions the party can perform, based on the authorization 
```

2024-06-12 16:55 UTC, cathyjung-da commented on docs/3.0.0/docs/concepts/ledger-model/ledger-structure.rst
> +(The difference between `@` and `&` will be explained in the :ref:`integrity section <da-signatories-maintainers>`.)
```suggestion
(The difference between `@` and `&` is explained in the :ref:`integrity section <da-signatories-maintainers>`.)
```

2024-06-21 06:23 UTC, yves-da commented
If this PR is still relevant, can you @hubert-da update it and then merge. Otherwise, please close it. Thank you.

2024-06-21 07:42 UTC, hubert-da commented
Yes, I will take care of it.

2024-06-25 08:57 UTC, hubert-da commented
FYI, I had to reapply the changes manually due to unresolvable conflicts.

2024-06-25 08:58 UTC, hubert-da commented on docs/3.1/docs/daml/reference/templates.rst
> +Users should remove any agreement declarations from their code, as this feature has been fully removed from the language.
This is a new change.

2024-06-25 08:58 UTC, hubert-da commented on docs/3.1/docs/tools/navigator/index.rst
> +Daml *contract ​templates* are ​models ​that contain ​all ​the ​applicable parameters ​and ​the ​choices ​that ​can ​be ​made ​in ​acting ​on ​that ​data.
This is new as well.

2024-06-26 13:49 UTC, cathyjung-da requested changes

2024-06-26 13:49 UTC, cathyjung-da commented on docs/3.1/docs/concepts/ledger-model/ledger-daml.rst
>  #. a set of allowed actions on the contracts, and
```suggestion
#. A set of allowed actions on the contracts
```

2024-06-26 13:49 UTC, cathyjung-da commented on docs/3.1/docs/concepts/ledger-model/ledger-daml.rst
>  #. the signatories, contract observers, and
```suggestion
#. The signatories, contract observers
```

2024-06-26 13:49 UTC, cathyjung-da commented on docs/3.1/docs/concepts/ledger-model/ledger-daml.rst
>  #. the optional key associated with each contract and its maintainers.
```suggestion
#. The optional key associated with each contract and its maintainers
```

2024-06-26 13:52 UTC, cathyjung-da approved these changes

2024-06-26 14:08 UTC, merged