Update bootstrap documentation
digital-asset/docs.daml.com pull request #673
Opened 2024-03-27 09:20 UTC by JoaoSa-da

2024-03-28 09:11 UTC, garyverhaegen-da commented
We have [started the 3.1 documentation folder "for real"](https://github.com/digital-asset/docs.daml.com/pull/675). This pull requests makes changes to 2.9.0; please consider whether this should be forward-ported to 3.1 before merging it.

2024-04-29 15:42 UTC, cathyjung-da commented on docs/2.9.0/docs/canton/usermanual/kms/external_key_storage/participant_kms_migration/participant_kms_migration.rst
> +and namespace <participant_kms_migration_new_namespace>`. The first option,
The comma does not fit here.

2024-04-29 15:42 UTC, cathyjung-da commented on docs/2.9.0/docs/canton/usermanual/kms/external_key_storage/participant_kms_migration/participant_kms_migration.rst
> +old and new domain have to use the same protocol version. Furthermore, the original root namespace key must
old and new domains

2024-05-02 13:24 UTC, soren-da commented on docs/2.9.0/docs/canton/usermanual/kms/external_key_storage/participant_kms_migration/participant_kms_migration_new_namespace.rst
> +    Currently this migration only works if you are migrating from an old participant node running protocol
important also that this only works for a single operator or if all other participant operators agree and follow the same steps (which you did not test here).

2024-05-03 13:07 UTC, JoaoSa-da commented on docs/2.9.0/docs/canton/usermanual/manage_participants.rst
> +does not control its own identity, when we do not want to store its identity key on the node for security
Well can we store the identity key in another place and still have `auto-init = true`?

2024-05-03 13:22 UTC, JoaoSa-da commented on docs/2.9.0/docs/canton/usermanual/kms/external_key_storage/participant_kms_migration/participant_kms_migration.rst
> +    This process applies to any type of Participant node migration, not just KMS-related ones.
I wanted to say that the processes we link here also work if we want to migrate to a participant that is not running KMS. But I guess it's misleading to mention it here.

2024-05-03 14:53 UTC, cathyjung-da requested changes

2024-05-03 14:53 UTC, cathyjung-da commented on docs/2.9.0/docs/canton/usermanual/kms/external_key_storage/participant_kms_migration/participant_kms_migration.rst
> +Therefore, we do not need to preserve the original root namespace key for a future migration. This works even if the
```suggestion
Therefore, you do not need to preserve the original root namespace key for a future migration. This works even if the
```
According to the style guide, using "we" and "one" as subjects is discouraged. Instead, "you" should be used.

2024-05-03 14:53 UTC, cathyjung-da commented on docs/2.9.0/docs/canton/usermanual/manage_participants.rst
> +2. When we do not want to store its identity key on the node for security reasons;
```suggestion
2. When you do not want to store its identity key on the node for security reasons;
```
According to the style guide, using "we" and "one" as subjects is discouraged. Instead, "you" should be used.

2024-05-03 14:53 UTC, cathyjung-da commented on docs/2.9.0/docs/canton/usermanual/manage_participants.rst
> +2. When we do not want to store its identity key on the node for security reasons;
```suggestion
2. When you do not want to store its identity key on the node for security reasons;
```
According to the style guide, using "we" and "one" as subjects is discouraged. Instead, "you" should be used.

2024-05-03 14:53 UTC, cathyjung-da commented on docs/2.9.0/docs/canton/usermanual/manage_participants.rst
> +3. When we want to set a participant's keys by ourselves.
```suggestion
3. When you want to set a participant's keys by yourself.
```

2024-05-29 12:50 UTC, soren-da approved these changes

2024-05-29 17:23 UTC, cathyjung-da requested changes

2024-05-29 17:23 UTC, cathyjung-da commented on docs/2.9.0/docs/canton/usermanual/kms/external_key_storage/participant_kms_migration/participant_kms_migration_new_namespace.rst
> +so that they refer to the new party ids. With this method, we can easily migrate our old participant
```suggestion
to refer to the new party ids. With this method, you can easily migrate your old participant
```

2024-05-29 17:23 UTC, cathyjung-da commented on docs/2.9.0/docs/canton/usermanual/kms/external_key_storage/participant_kms_migration/participant_kms_migration_new_namespace.rst
> +protocol version. Furthermore, we do not need to safe-keep the old node's root namespace key because
```suggestion
protocol version. Furthermore, you do not need to safe-keep the old node's root namespace key, because
```

2024-05-29 17:23 UTC, cathyjung-da commented on docs/2.9.0/docs/canton/usermanual/kms/external_key_storage/participant_kms_migration/participant_kms_migration_new_namespace.rst
> +our participant namespace changes. However, for it to work a single operator must control
```suggestion
your participant namespace changes. However, for it to work a single operator must control
```

2024-05-29 17:23 UTC, cathyjung-da commented on docs/2.9.0/docs/canton/usermanual/kms/external_key_storage/participant_kms_migration/participant_kms_migration_new_namespace.rst
> +re-write the party ids mentioned in those contracts to match the new party ids. We can then connect to the new sync domain:
```suggestion
re-write the party ids mentioned in those contracts to match the new party ids. You can then connect to the new sync domain:
```

2024-05-29 17:23 UTC, cathyjung-da commented on docs/2.9.0/docs/canton/usermanual/kms/external_key_storage/participant_kms_migration/participant_kms_migration_same_namespace.rst
> +transfer the data from the old node to the new one. In this example, we do not only transfer the parties, contracts and DARs,
```suggestion
transfer the data from the old node to the new one. In this example, you transfer the parties, contracts, and DARs,
```

2024-05-29 17:23 UTC, cathyjung-da commented on docs/2.9.0/docs/canton/usermanual/kms/external_key_storage/participant_kms_migration/participant_kms_migration_same_namespace.rst
> +but we also transfer the node's identity, and thus, both old and new participant will share the
```suggestion
along with the node's identity. Thus, both the old and new participants share the
```

2024-05-29 17:23 UTC, cathyjung-da commented on docs/2.9.0/docs/canton/usermanual/kms/external_key_storage/participant_kms_migration/participant_kms_migration_same_namespace.rst
> +same namespace. This has the advantage that it can be done in a multi-operator setting when the other operators
```suggestion
same namespace. This has the advantage of being feasible in a multi-operator setting even when the other operators
```

2024-05-29 17:23 UTC, cathyjung-da commented on docs/2.9.0/docs/canton/usermanual/kms/external_key_storage/participant_kms_migration/participant_kms_migration_same_namespace.rst
> +    This is necessary because we require signing topology transactions with the root namespace key everytime
```suggestion
    This is necessary because you need to sign topology transactions with the root namespace key everytime
```

2024-05-29 17:23 UTC, cathyjung-da commented on docs/2.9.0/docs/canton/usermanual/kms/external_key_storage/participant_kms_migration/participant_kms_migration_same_namespace.rst
> +    we migrate a node to a new protocol version that is not supported by the old domain.
```suggestion
    you migrate a node to a new protocol version that is not supported by the old domain.
```

2024-05-29 17:23 UTC, cathyjung-da commented on docs/2.9.0/docs/canton/usermanual/manage_domain_entities.rst
> +However, there are situations where a node should not be automatically initialized, but where we prefer to control
```suggestion
However, there are situations where a node should not be automatically initialized, but where you prefer to control
```

2024-05-29 17:23 UTC, cathyjung-da commented on docs/2.9.0/docs/canton/usermanual/manage_domain_entities.rst
> +reasons, or when we want to set our own keys (e.g. when keys are externally stored in a Key Management Service - KMS).
```suggestion
reasons, or when you want to set your own keys (e.g. when keys are externally stored in a Key Management Service - KMS).
```

2024-05-29 17:23 UTC, cathyjung-da commented on docs/2.9.0/docs/canton/usermanual/manage_domain_entities.rst
> +   The following sections assume that we are using Canton keys and that we do not have a KMS set-up. If you are running
```suggestion
   The following sections assume that you are using Canton keys and that you do not have a KMS set-up. If you are running
```

2024-05-29 17:23 UTC, cathyjung-da commented on docs/2.9.0/docs/canton/usermanual/manage_domain_entities.rst
> +If the sync domain manager has ``auto-init = true`` (the default value) we need to make sure that the
```suggestion
If the sync domain manager has ``auto-init = true`` (the default value) you need to make sure that the
```

2024-05-29 17:23 UTC, cathyjung-da commented on docs/2.9.0/docs/canton/usermanual/manage_domain_entities.rst
> +identity is generated and ready before we can bootstrap the sync domain:
```suggestion
identity is generated and ready before you can bootstrap the sync domain:
```

2024-05-29 17:23 UTC, cathyjung-da commented on docs/2.9.0/docs/canton/usermanual/manage_participants.rst
> +We reiterate again the fact that if you are using a Key Management Service (KMS) to handle Canton's keys
```suggestion
If you are using a Key Management Service (KMS) to handle Canton's keys
```

2024-05-30 14:48 UTC, cathyjung-da requested changes

2024-05-30 14:48 UTC, cathyjung-da commented on docs/2.7.9/docs/canton/usermanual/identity_management.rst
>  In the following, we demonstrate the basic steps how to initialise a node:
```suggestion
The following demonstrates the basic steps on how to initialize a node:
```

2024-05-30 14:48 UTC, cathyjung-da commented on docs/2.7.9/docs/canton/usermanual/identity_management.rst
>  There are situations where a node should not be automatically initialized, but where we prefer to control
```suggestion
There are situations where a node should not be automatically initialized, but where you should control
```

2024-05-30 14:48 UTC, cathyjung-da commented on docs/2.7.9/docs/canton/usermanual/identity_management.rst
>  each step of the initialization. For example, when a node in the setup does
```suggestion
each step of the initialization. For example, this might be the case when a node in the setup does
```

2024-05-30 14:48 UTC, cathyjung-da commented on docs/2.8.5/docs/canton/usermanual/identity_management.rst
>  There are situations where a node should not be automatically initialized, but where we prefer to control
```suggestion
There are situations where a node should not be automatically initialized, but where you should control
```

2024-05-30 14:48 UTC, cathyjung-da commented on docs/2.8.5/docs/canton/usermanual/identity_management.rst
>  each step of the initialization. For example, when a node in the setup does
```suggestion
each step of the initialization. For example, this might be the case when a node in the setup does
```

2024-05-30 14:48 UTC, cathyjung-da commented on docs/2.8.5/docs/canton/usermanual/identity_management.rst
>  In the following, we demonstrate the basic steps how to initialise a node:
```suggestion
The following demonstrates the basic steps on how to initialize a node:
```

2024-05-30 14:48 UTC, cathyjung-da commented on docs/3.1/docs/canton/usermanual/identity_management.rst
>  There are situations where a node should not be automatically initialized, but where we prefer to control
```suggestion
There are situations where a node should not be automatically initialized, but where you should control
```

2024-05-30 14:48 UTC, cathyjung-da commented on docs/3.1/docs/canton/usermanual/identity_management.rst
>  each step of the initialization. For example, when a node in the setup does
```suggestion
each step of the initialization. For example, this might be the case when a node in the setup does
```

2024-05-30 14:48 UTC, cathyjung-da commented on docs/3.1/docs/canton/usermanual/identity_management.rst
>  reasons, or when we want to set our own keys (e.g. when keys are externally stored in a Key Management Service - KMS).
```suggestion
reasons, or when you want to set our own keys (e.g. when keys are externally stored in a Key Management Service - KMS).
```

2024-05-30 14:48 UTC, cathyjung-da commented on docs/3.1/docs/canton/usermanual/identity_management.rst
>  In the following, we demonstrate the basic steps of how to initialize a node:
```suggestion
The following demonstrates the basic steps on how to initialize a node:
```

2024-05-30 15:00 UTC, cathyjung-da approved these changes

2024-06-03 11:18 UTC, merged